name: Derivation Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-derivation:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest jsonschema
    
    - name: Validate coverage report schema
      run: |
        echo "=== Validating coverage report schema ==="
        python -c "
        import json
        import jsonschema
        
        # Load schema
        with open('08_CI_CD/schemas/coverage_report.schema.json') as f:
            schema = json.load(f)
        
        # Load report
        with open('01_PUBLISHED/winner_HEAD_0020_v522B/coverage_report.json') as f:
            report = json.load(f)
        
        # Validate
        jsonschema.validate(report, schema)
        print('✅ Schema validation passed')
        "
    
    - name: Check derivation invariants
      run: |
        echo "=== Checking derivation invariants ==="
        python 07_TOOLS/validation/validate_derivation.py
    
    - name: Run red team tests
      run: |
        echo "=== Running red team attack tests ==="
        make red-team
    
    - name: Verify tail derivation
      run: |
        echo "=== Verifying tail derivation ==="
        python -c "
        import json
        
        # Load coverage report
        with open('01_PUBLISHED/winner_HEAD_0020_v522B/coverage_report.json') as f:
            report = json.load(f)
        
        # Check critical invariants
        assert report['pt_sha256_bundle'] == report['pt_sha256_derived'], 'SHA mismatch!'
        assert report['tail_derivation_verified'] == True, 'Tail not verified!'
        assert report['gates_head_only'] == True, 'Gates not head-only!'
        assert report['no_tail_guard'] == True, 'Tail guard present!'
        
        print('✅ All derivation invariants satisfied')
        print(f\"   SHA: {report['pt_sha256_bundle'][:16]}...\")
        print(f\"   Tail verified: {report['tail_derivation_verified']}\")
        print(f\"   Note: {report['derivation_note']}\")
        "
    
    - name: Run full validation
      run: |
        echo "=== Running full validation suite ==="
        make validate-all