#!/usr/bin/env python3
"""
Verify the known plaintexts for K1, K2, K3
"""

# Known plaintexts
K1_PLAINTEXT = "BETWEENSUBTLESHADINGANDTHEABSENCEOFLIGHTLIESTHENUANCEOFIQLUSION"
K2_PLAINTEXT = "ITWASTOTALLYINVISIBLEHOWSTHATPOSSIBLE?THEYUSEDTHEEARTHSMAGNETICFIELDXTHEINFORMATIONWASGATHEREDANDTRANSMITTEDUNDERGRUUNDTOANUNKNOWNLOCATIONXDOESLANGLEYKNOWABOUTTHIS?THEYSHOULDITSBURIEDOUTTHERESOMEWHEREXWHOKNOWSTHEEXACTLOCATION?ONLYWWTHISWASHISLASTMESSAGEXTHIRTYEIGHTDEGREESFIFTYSEVENMINUTESSIXPOINTFIVESECONDSNORTHSEVENTYSEVENDEGREESEIGHTMINUTESFORTYFOURSECONDSWESTIDBYROWS"
K3_PLAINTEXT = "SLOWLYDESPARATLYSLOWLYTHEREMAINSOFPASSAGEDEBRISTHATENCUMBEREDTHELOWERPARTOFTHEDOORWAYWASREMOVEDWITHTREMBLINGHANDSIMADEATINYBREACHINTHEUPPERLEFTHANDCORNERANDTHENWIDENINGTHEHOLEALITTLEIINSERTEDTHECANDLEANDPEEREDINTHEHOTAIRCAPINGFROMTHECHAMBERCAUSEDTHEFLAMETOFLICKERBUTPRESENTLYDETAILSOFTHEROOMWITHINEMERGEDFROMTHEMISTXCANYOUSEEANYTHINGQ"

print("K1 length:", len(K1_PLAINTEXT), "chars")
print("K1 text:", K1_PLAINTEXT[:50], "...")
print()
print("K2 length:", len(K2_PLAINTEXT), "chars")
print("K2 text:", K2_PLAINTEXT[:50], "...")
print()
print("K3 length:", len(K3_PLAINTEXT), "chars")  
print("K3 text:", K3_PLAINTEXT[:50], "...")

# Check unique sections in ticks file
import pandas as pd

ticks_df = pd.read_csv("04_full_sculpture/kryptos_full_sculpture_ticks.csv")
print("\nSections in ticks file:")
for section in ticks_df['section'].unique():
    section_df = ticks_df[ticks_df['section'] == section]
    max_idx = section_df['section_index'].max()
    count = len(section_df)
    print(f"  {section}: max_index={max_idx}, count={count}")