name: Validate Bundles

on:
  push:
  pull_request:
  schedule:
    - cron: "0 3 * * *"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Validate published bundles
        run: |
          python scripts/tools/validate_bundle.py results/GRID_ONLY --schema scripts/schema
          python scripts/tools/validate_bundle.py experiments --schema scripts/schema --mode lenient
          bash tests/schema/test_validation.sh
  policy-hash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check policy hashes
        run: |
          set -e
          for reg in data/registry/*.sha256; do
            [ -f "$reg" ] || continue
            expected=$(cut -d' ' -f1 "$reg")
            target=$(cut -d' ' -f2 "$reg")
            actual=$(sha256sum "$target" | cut -d' ' -f1)
            [ "$actual" = "$expected" ] || (echo "hash mismatch for $target"; exit 1)
          done
  manifest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Verify manifests
        run: |
          python scripts/tools/make_manifest.py results /tmp/results_manifest.sha256
          diff -u /tmp/results_manifest.sha256 results/MANIFEST.sha256
          python scripts/tools/make_manifest.py data /tmp/data_manifest.sha256
          diff -u /tmp/data_manifest.sha256 data/MANIFEST.sha256
