name: Verify Experiments

on:
  push:
    branches: [ main, experiment-* ]
  pull_request:
    branches: [ main ]

jobs:
  verify-manifests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Verify Cadence Panel Manifest
      run: |
        cd experiments/cadence_panel/runs/2025-09-05
        while IFS=' ' read -r expected_hash file_path; do
          if [ -f "$file_path" ]; then
            actual_hash=$(sha256sum "$file_path" | cut -d' ' -f1)
            if [ "$expected_hash" != "$actual_hash" ]; then
              echo "Hash mismatch for $file_path"
              echo "Expected: $expected_hash"
              echo "Actual: $actual_hash"
              exit 1
            fi
          fi
        done < MANIFEST.sha256
        echo "Cadence panel manifest verified"
    
    - name: Verify Alternates Manifest
      run: |
        cd experiments/alternates/runs/2025-09-05
        while IFS=' ' read -r expected_hash file_path; do
          if [ -f "$file_path" ]; then
            actual_hash=$(sha256sum "$file_path" | cut -d' ' -f1)
            if [ "$expected_hash" != "$actual_hash" ]; then
              echo "Hash mismatch for $file_path"
              echo "Expected: $expected_hash"
              echo "Actual: $actual_hash"
              exit 1
            fi
          fi
        done < MANIFEST.sha256
        echo "Alternates manifest verified"
    
    - name: Check for Codenames
      run: |
        # Check for forbidden codenames in public docs
        if grep -r -i -E "Faraday|Janus|Tycho|Luma|Hermes|Flock|Explainer|Sparrow" \
           --include="*.md" --include="*.txt" --include="*.json" \
           --exclude-dir=results --exclude-dir=release --exclude-dir=.git .; then
          echo "Error: Forbidden codenames found in public documents"
          exit 1
        fi
        echo "No codenames found in public documents"
    
    - name: Verify Seed Consistency
      run: |
        # Check that seed 1337 is used consistently
        if grep -r "seed" experiments/*/runs/2025-09-05/*.md | grep -v "1337" | grep -v "seed_worker"; then
          echo "Warning: Non-standard seed found"
        fi
        echo "Seed consistency check complete"